#!/usr/bin/env python3

# SPDX-FileComment: finnix-collector-mirrors
# SPDX-FileCopyrightText: Copyright (C) 2022 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

import sys
import rf_collectors.finnix_mirrors


def module_init():
    if __name__ == "__main__":
        sys.exit(rf_collectors.finnix_mirrors.main(sys.argv))


module_init()
