#!/usr/bin/env python3

# SPDX-FileComment: gps-collector
# SPDX-FileCopyrightText: Copyright (C) 2021 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

import sys
import rf_collectors.gps


def module_init():
    if __name__ == "__main__":
        sys.exit(rf_collectors.gps.main(sys.argv))


module_init()
