#!/usr/bin/env python3

# SPDX-FileComment: prometheus-livepatch
# SPDX-FileCopyrightText: Copyright (C) 2021 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

import sys
import prometheus_collectors.livepatch


def module_init():
    if __name__ == "__main__":
        sys.exit(prometheus_collectors.livepatch.main(sys.argv))


module_init()
